Name = input("Please enter your name: ")
Age = input("Please enter your age: ")
DOB = input("Please enter your date of birth: ")
print("your name is: " + Name)
print("your age is: " + Age)
print("your date of birth is: " + DOB)